version: '3.9'
services:
  chat-node:
    build: .
    command: npm run dev:watch
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb
    volumes:
      - .:/src/
    depends_on:
      - mongodb
    links:
      - mongodb
  
  mongodb:
    image: mongo:4.0
    ports:
      - 27017:27017